#!/usr/bin/env bash
set -euo pipefail

RESULT_FILE="${1:-results.json}"

# Check if result file exists
if [ ! -f "$RESULT_FILE" ]; then
    echo "Error: Result file not found: $RESULT_FILE"
    exit 1
fi

# Check if we have any results
if [ ! -s "$RESULT_FILE" ] || [ "$(jq length "$RESULT_FILE")" -eq 0 ]; then
    echo "No results to post"
    exit 0
fi

# Extract PR number from GitHub ref
PR_NUMBER="${GITHUB_REF##*/}"
if [ -z "$PR_NUMBER" ] || [ "$PR_NUMBER" = "refs/heads/main" ] || [ "$PR_NUMBER" = "refs/heads/master" ]; then
    echo "Error: Could not extract PR number from GITHUB_REF: $GITHUB_REF"
    echo "This action should only run on pull request events"
    exit 1
fi

echo "Posting results to PR #$PR_NUMBER"

# Build comment body
COMMENT_BODY="### 🤖 AutoAgent Results

"

# Process each result
while read -r LINE; do
    RULE=$(echo "$LINE" | jq -r '.rule')
    OUTPUT=$(echo "$LINE" | jq -r '.output')
    
    # Escape markdown special characters in output
    OUTPUT_ESCAPED=$(echo "$OUTPUT" | sed 's/\\/\\\\/g' | sed 's/`/\\`/g' | sed 's/\*/\\*/g' | sed 's/_/\\_/g' | sed 's/\[/\\[/g' | sed 's/\]/\\]/g')
    
    COMMENT_BODY+="**Rule:** \`$RULE\`\n"
    COMMENT_BODY+="\`\`\`\n$OUTPUT_ESCAPED\n\`\`\`\n\n"
done < <(jq -c '.[]' "$RESULT_FILE")

# Add footer
COMMENT_BODY+="---\n"
COMMENT_BODY+="*Generated by [AutoAgent](https://github.com/erans/autoagent) v1.0*"

echo "Comment body prepared (${#COMMENT_BODY} characters)"

# Post comment using GitHub CLI
if command -v gh >/dev/null 2>&1; then
    echo "$COMMENT_BODY" | gh pr comment "$PR_NUMBER" --body -
    echo "Comment posted successfully to PR #$PR_NUMBER"
else
    echo "Error: GitHub CLI (gh) not found. Cannot post comment."
    echo "Please ensure the GitHub CLI is available in the runner environment."
    echo "Comment that would have been posted:"
    echo "---"
    echo -e "$COMMENT_BODY"
    echo "---"
    exit 1
fi
